language: ruby
rvm:
    - 2.1
addons:
    apt:
        packages:
            - python3
            - python3-pip
            - sshpass

install:
    - pip3 install --user -r requirements.txt
    - gem install bundle

script:
    - ./_scripts/build.sh
    - ./_scripts/deploy.sh
    - ./_scripts/check_new_posts.sh

