language: ruby
rvm:
    - 2.6
addons:
    apt:
        packages:
            - python3
            - python3-pip
            - python3-setuptools
            - sshpass

install:
    - pip install --user --upgrade pip
    - pip3 install --user --upgrade pip
    - pip3 install --user -r requirements.txt
    - gem install bundle

script:
    - ./_scripts/build.sh
    - ./_scripts/deploy.sh
    - ./_scripts/check_new_posts.sh

