language: ruby
rvm:
    - 2.6
    
addons:
    apt:
        packages:
            - python3
            - python3-pip
            - python3-setuptools
            - sshpass

install:
    - sudo apt-get install python-pip python3-pip --yes
    - sudo python3 -m pip install pip --upgrade --force
    - sudo python -m pip install pip --upgrade --force
    - pip3 install --user -r requirements.txt
    - gem install bundle

script:
    - ./_scripts/build.sh
    - ./_scripts/deploy.sh
    - ./_scripts/check_new_posts.sh

branches:
    only: 
        - master