language: ruby
branhces:
    only: master
rvm:
    - 2.1
addons:
    apt:
        packages:
            - python3
            - python3-pip
            - sshpass

before_install:
    - pip3 install --user -r requirements.txt

script:
    - ./_scripts/check_new_posts.sh
    - ./_scripts/deploy.sh

