language: ruby
rvm:
    - 2.1
addons:
    apt:
        packages:
            - python3
            - python3-pip
            - sshpass

before_install:
    - pip3 install --user -r requirements.txt

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./_scripts/travis_deploy.sh; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./_scripts/build.sh; fi'

